services:
  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306 # Container:Host
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  mongo:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  express:
    build: ./express/
    container_name: "express-api-demo"
    image: "allan-express-api"
    ports:
      - "3000:3000"

  fastify:
    build: ./fastify-api/
    container_name: "fastify-api-demo"
    image: "allan-fastify-api"
    ports:
      - "3001:3001"
      
volumes:
  mysqldb-db: