version: "3"

services:
  elasticsearch:
    image: "elasticsearch:7.4.0"
    hostname: "elasticsearch"
    container_name: "elasticsearch"
    environment:
      discovery.type: "single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
volumes:
  elasticsearch_data: