version: "3"

services:
  mysqldb:
    image: mysql:latest
    hostname: "mysqldb"
    container_name: "mysqldb"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysqldb-db:/var/lib/mysql
volumes:
  mysqldb-db: