version: '3'

services:
  neo4j:
    image: 'bitnami/neo4j:3'
    hostname: "neo4j"
    container_name: "neo4j"
    restart: always
    environment:
      NEO4J_PASSWORD: "Dev@Password"
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - 'neo4j_data:/bitnami'

volumes:
  neo4j_data: