version: "3"

services:
  mongodb.alpine:
    image: mvertes/alpine-mongo
    hostname: "mongodb.alpine"
    container_name: "mongodb.alpine"
    ports:
    - "27017:27017"
    volumes:
    - mongo_alpine_data:/data/db
volumes:
  mongo_alpine_data: